### ISSUE TITLE
テスティング & 測定ツール

### ISSUE THREAD

**Issue by amylase** [osak/ISUCON5-practice#8]
- [x] webサービス（参照実装）が与えられるので、アクセスのシーケンスに対するレスポンスを集めて回帰テストするツール
- [x] それらのケースをたくさん投げて性能を測定するツール

**Comment by osak** [comment]
ブラウザ上の操作をロギングして自動実行してくれるようなやつがあるとよい（たぶん既存のアプリケーションである）

**Comment by osak** [comment]
JMeterがよさそう http://jmeter.apache.org/

**Comment by osak** [comment]
mkutがプロになった
